package fr.nkri.wizapi.utils.translate;

import java.util.HashMap;
import java.util.Map;

/**
 * Utility class for translating Minecraft 1.8.8 entity and material names
 * from English to French
 */
public class WizTranslator {

    private static Map<String, String> translations = new HashMap<String, String>();

    static {
        initTranslations();
    }

    /**
     * Translates the name into French
     *
     * @param text text to convert
     * @return The name translated into French, or the English name if no translation exists
     */
    public static String translateMaterial(final String text) {
        if (translations == null) {
            return "Inconnu";
        }

        return translations.getOrDefault(text, text);
    }

    private static void initTranslations() {
        translations.put("AIR", "Air");
        translations.put("STONE", "Pierre");
        translations.put("GRASS", "Herbe");
        translations.put("DIRT", "Terre");
        translations.put("COBBLESTONE", "Pierre taillée");
        translations.put("WOOD", "Bois");
        translations.put("SAPLING", "Pousse d'arbre");
        translations.put("BEDROCK", "Roche mère");
        translations.put("WATER", "Eau");
        translations.put("STATIONARY_WATER", "Eau stationnaire");
        translations.put("LAVA", "Lave");
        translations.put("STATIONARY_LAVA", "Lave stationnaire");
        translations.put("SAND", "Sable");
        translations.put("GRAVEL", "Gravier");
        translations.put("GOLD_ORE", "Minerai d'or");
        translations.put("IRON_ORE", "Minerai de fer");
        translations.put("COAL_ORE", "Minerai de charbon");
        translations.put("LOG", "Bûche");
        translations.put("LEAVES", "Feuilles");
        translations.put("SPONGE", "Éponge");
        translations.put("GLASS", "Verre");
        translations.put("LAPIS_ORE", "Minerai de lapis-lazuli");
        translations.put("LAPIS_BLOCK", "Bloc de lapis-lazuli");
        translations.put("DISPENSER", "Distributeur");
        translations.put("SANDSTONE", "Grès");
        translations.put("NOTE_BLOCK", "Bloc musical");
        translations.put("BED_BLOCK", "Lit");
        translations.put("POWERED_RAIL", "Rail de propulsion");
        translations.put("DETECTOR_RAIL", "Rail détecteur");
        translations.put("PISTON_STICKY_BASE", "Piston collant");
        translations.put("WEB", "Toile d'araignée");
        translations.put("LONG_GRASS", "Hautes herbes");
        translations.put("DEAD_BUSH", "Buisson mort");
        translations.put("PISTON_BASE", "Piston");
        translations.put("PISTON_EXTENSION", "Extension de piston");
        translations.put("WOOL", "Laine");
        translations.put("PISTON_MOVING_PIECE", "Pièce de piston en mouvement");
        translations.put("YELLOW_FLOWER", "Fleur jaune");
        translations.put("RED_ROSE", "Rose");
        translations.put("BROWN_MUSHROOM", "Champignon brun");
        translations.put("RED_MUSHROOM", "Champignon rouge");
        translations.put("GOLD_BLOCK", "Bloc d'or");
        translations.put("IRON_BLOCK", "Bloc de fer");
        translations.put("DOUBLE_STEP", "Double dalle");
        translations.put("STEP", "Dalle");
        translations.put("BRICK", "Brique");
        translations.put("TNT", "TNT");
        translations.put("BOOKSHELF", "Bibliothèque");
        translations.put("MOSSY_COBBLESTONE", "Pierre taillée moussue");
        translations.put("OBSIDIAN", "Obsidienne");
        translations.put("TORCH", "Torche");
        translations.put("FIRE", "Feu");
        translations.put("MOB_SPAWNER", "Générateur de monstres");
        translations.put("WOOD_STAIRS", "Escalier en bois");
        translations.put("CHEST", "Coffre");
        translations.put("REDSTONE_WIRE", "Fil de redstone");
        translations.put("DIAMOND_ORE", "Minerai de diamant");
        translations.put("DIAMOND_BLOCK", "Bloc de diamant");
        translations.put("WORKBENCH", "Établi");
        translations.put("CROPS", "Cultures");
        translations.put("SOIL", "Terre labourée");
        translations.put("FURNACE", "Fourneau");
        translations.put("BURNING_FURNACE", "Fourneau allumé");
        translations.put("SIGN_POST", "Panneau");
        translations.put("WOODEN_DOOR", "Porte en bois");
        translations.put("LADDER", "Échelle");
        translations.put("RAILS", "Rails");
        translations.put("COBBLESTONE_STAIRS", "Escalier en pierre taillée");
        translations.put("WALL_SIGN", "Panneau mural");
        translations.put("LEVER", "Levier");
        translations.put("STONE_PLATE", "Plaque de pression en pierre");
        translations.put("IRON_DOOR_BLOCK", "Bloc de porte en fer");
        translations.put("WOOD_PLATE", "Plaque de pression en bois");
        translations.put("REDSTONE_ORE", "Minerai de redstone");
        translations.put("GLOWING_REDSTONE_ORE", "Minerai de redstone lumineux");
        translations.put("REDSTONE_TORCH_OFF", "Torche de redstone éteinte");
        translations.put("REDSTONE_TORCH_ON", "Torche de redstone allumée");
        translations.put("STONE_BUTTON", "Bouton en pierre");
        translations.put("SNOW", "Neige");
        translations.put("ICE", "Glace");
        translations.put("SNOW_BLOCK", "Bloc de neige");
        translations.put("CACTUS", "Cactus");
        translations.put("CLAY", "Argile");
        translations.put("SUGAR_CANE_BLOCK", "Canne à sucre");
        translations.put("JUKEBOX", "Juke-box");
        translations.put("FENCE", "Barrière");
        translations.put("PUMPKIN", "Citrouille");
        translations.put("NETHERRACK", "Roche du Nether");
        translations.put("SOUL_SAND", "Sable des âmes");
        translations.put("GLOWSTONE", "Pierre lumineuse");
        translations.put("PORTAL", "Portail");
        translations.put("JACK_O_LANTERN", "Citrouille d'Halloween");
        translations.put("CAKE_BLOCK", "Gâteau");
        translations.put("DIODE_BLOCK_OFF", "Répéteur éteint");
        translations.put("DIODE_BLOCK_ON", "Répéteur allumé");
        translations.put("STAINED_GLASS", "Verre teinté");
        translations.put("TRAP_DOOR", "Trappe");
        translations.put("MONSTER_EGGS", "Œufs de monstre");
        translations.put("SMOOTH_BRICK", "Pierre lisse");
        translations.put("HUGE_MUSHROOM_1", "Énorme champignon brun");
        translations.put("HUGE_MUSHROOM_2", "Énorme champignon rouge");
        translations.put("IRON_FENCE", "Barreaux de fer");
        translations.put("THIN_GLASS", "Vitre");
        translations.put("MELON_BLOCK", "Melon");
        translations.put("PUMPKIN_STEM", "Tige de citrouille");
        translations.put("MELON_STEM", "Tige de melon");
        translations.put("VINE", "Vigne");
        translations.put("FENCE_GATE", "Portillon");
        translations.put("BRICK_STAIRS", "Escalier en briques");
        translations.put("SMOOTH_STAIRS", "Escalier en pierre lisse");
        translations.put("MYCEL", "Mycélium");
        translations.put("WATER_LILY", "Nénuphar");
        translations.put("NETHER_BRICK", "Brique du Nether");
        translations.put("NETHER_FENCE", "Barrière en brique du Nether");
        translations.put("NETHER_BRICK_STAIRS", "Escalier en brique du Nether");
        translations.put("NETHER_WARTS", "Verrues du Nether");
        translations.put("ENCHANTMENT_TABLE", "Table d'enchantement");
        translations.put("BREWING_STAND", "Alambic");
        translations.put("CAULDRON", "Chaudron");
        translations.put("ENDER_PORTAL", "Portail de l'End");
        translations.put("ENDER_PORTAL_FRAME", "Cadre de portail de l'End");
        translations.put("ENDER_STONE", "Pierre de l'End");
        translations.put("DRAGON_EGG", "Œuf de dragon");
        translations.put("REDSTONE_LAMP_OFF", "Lampe de redstone éteinte");
        translations.put("REDSTONE_LAMP_ON", "Lampe de redstone allumée");
        translations.put("WOOD_DOUBLE_STEP", "Double dalle en bois");
        translations.put("WOOD_STEP", "Dalle en bois");
        translations.put("COCOA", "Cacao");
        translations.put("SANDSTONE_STAIRS", "Escalier en grès");
        translations.put("EMERALD_ORE", "Minerai d'émeraude");
        translations.put("ENDER_CHEST", "Coffre de l'Ender");
        translations.put("TRIPWIRE_HOOK", "Crochet de fil-piège");
        translations.put("TRIPWIRE", "Fil-piège");
        translations.put("EMERALD_BLOCK", "Bloc d'émeraude");
        translations.put("SPRUCE_WOOD_STAIRS", "Escalier en bois de sapin");
        translations.put("BIRCH_WOOD_STAIRS", "Escalier en bois de bouleau");
        translations.put("JUNGLE_WOOD_STAIRS", "Escalier en bois de jungle");
        translations.put("COMMAND", "Bloc de commande");
        translations.put("BEACON", "Balise");
        translations.put("COBBLE_WALL", "Muret en pierre taillée");
        translations.put("FLOWER_POT", "Pot de fleur");
        translations.put("CARROT", "Carotte");
        translations.put("POTATO", "Pomme de terre");
        translations.put("WOOD_BUTTON", "Bouton en bois");
        translations.put("SKULL", "Crâne");
        translations.put("ANVIL", "Enclume");
        translations.put("TRAPPED_CHEST", "Coffre piégé");
        translations.put("GOLD_PLATE", "Plaque de pression pondérée (légère)");
        translations.put("IRON_PLATE", "Plaque de pression pondérée (lourde)");
        translations.put("REDSTONE_COMPARATOR_OFF", "Comparateur éteint");
        translations.put("REDSTONE_COMPARATOR_ON", "Comparateur allumé");
        translations.put("DAYLIGHT_DETECTOR", "Capteur de lumière du jour");
        translations.put("REDSTONE_BLOCK", "Bloc de redstone");
        translations.put("QUARTZ_ORE", "Minerai de quartz");
        translations.put("HOPPER", "Entonnoir");
        translations.put("QUARTZ_BLOCK", "Bloc de quartz");
        translations.put("QUARTZ_STAIRS", "Escalier en quartz");
        translations.put("ACTIVATOR_RAIL", "Rail activateur");
        translations.put("DROPPER", "Dropper");
        translations.put("STAINED_CLAY", "Argile teintée");
        translations.put("HAY_BLOCK", "Botte de foin");
        translations.put("CARPET", "Tapis");
        translations.put("HARD_CLAY", "Argile durcie");
        translations.put("COAL_BLOCK", "Bloc de charbon");
        translations.put("PACKED_ICE", "Glace compactée");
        translations.put("DOUBLE_PLANT", "Plante double");
        translations.put("STANDING_BANNER", "Bannière");
        translations.put("WALL_BANNER", "Bannière murale");
        translations.put("DAYLIGHT_DETECTOR_INVERTED", "Capteur de lumière du jour inversé");
        translations.put("RED_SANDSTONE", "Grès rouge");
        translations.put("RED_SANDSTONE_STAIRS", "Escalier en grès rouge");
        translations.put("DOUBLE_STONE_SLAB2", "Double dalle de pierre 2");
        translations.put("STONE_SLAB2", "Dalle de pierre 2");
        translations.put("SPRUCE_FENCE_GATE", "Portillon en bois de sapin");
        translations.put("BIRCH_FENCE_GATE", "Portillon en bois de bouleau");
        translations.put("JUNGLE_FENCE_GATE", "Portillon en bois de jungle");
        translations.put("DARK_OAK_FENCE_GATE", "Portillon en bois de chêne noir");
        translations.put("ACACIA_FENCE_GATE", "Portillon en bois d'acacia");
        translations.put("SPRUCE_FENCE", "Barrière en bois de sapin");
        translations.put("BIRCH_FENCE", "Barrière en bois de bouleau");
        translations.put("JUNGLE_FENCE", "Barrière en bois de jungle");
        translations.put("DARK_OAK_FENCE", "Barrière en bois de chêne noir");
        translations.put("ACACIA_FENCE", "Barrière en bois d'acacia");
        translations.put("IRON_SPADE", "Pelle en fer");
        translations.put("IRON_PICKAXE", "Pioche en fer");
        translations.put("IRON_AXE", "Hache en fer");
        translations.put("FLINT_AND_STEEL", "Briquet");
        translations.put("APPLE", "Pomme");
        translations.put("BOW", "Arc");
        translations.put("ARROW", "Flèche");
        translations.put("COAL", "Charbon");
        translations.put("DIAMOND", "Diamant");
        translations.put("IRON_INGOT", "Lingot de fer");
        translations.put("GOLD_INGOT", "Lingot d'or");
        translations.put("IRON_SWORD", "Épée en fer");
        translations.put("WOOD_SWORD", "Épée en bois");
        translations.put("WOOD_SPADE", "Pelle en bois");
        translations.put("WOOD_PICKAXE", "Pioche en bois");
        translations.put("WOOD_AXE", "Hache en bois");
        translations.put("STONE_SWORD", "Épée en pierre");
        translations.put("STONE_SPADE", "Pelle en pierre");
        translations.put("STONE_PICKAXE", "Pioche en pierre");
        translations.put("STONE_AXE", "Hache en pierre");
        translations.put("DIAMOND_SWORD", "Épée en diamant");
        translations.put("DIAMOND_SPADE", "Pelle en diamant");
        translations.put("DIAMOND_PICKAXE", "Pioche en diamant");
        translations.put("DIAMOND_AXE", "Hache en diamant");
        translations.put("STICK", "Bâton");
        translations.put("BOWL", "Bol");
        translations.put("MUSHROOM_SOUP", "Soupe de champignons");
        translations.put("GOLD_SWORD", "Épée en or");
        translations.put("GOLD_SPADE", "Pelle en or");
        translations.put("GOLD_PICKAXE", "Pioche en or");
        translations.put("GOLD_AXE", "Hache en or");
        translations.put("STRING", "Fil");
        translations.put("FEATHER", "Plume");
        translations.put("SULPHUR", "Poudre à canon");
        translations.put("WOOD_HOE", "Houe en bois");
        translations.put("STONE_HOE", "Houe en pierre");
        translations.put("IRON_HOE", "Houe en fer");
        translations.put("DIAMOND_HOE", "Houe en diamant");
        translations.put("GOLD_HOE", "Houe en or");
        translations.put("SEEDS", "Graines");
        translations.put("WHEAT", "Blé");
        translations.put("BREAD", "Pain");
        translations.put("LEATHER_HELMET", "Casque en cuir");
        translations.put("LEATHER_CHESTPLATE", "Tunique en cuir");
        translations.put("LEATHER_LEGGINGS", "Pantalon en cuir");
        translations.put("LEATHER_BOOTS", "Bottes en cuir");
        translations.put("CHAINMAIL_HELMET", "Casque en mailles");
        translations.put("CHAINMAIL_CHESTPLATE", "Plastron en mailles");
        translations.put("CHAINMAIL_LEGGINGS", "Jambières en mailles");
        translations.put("CHAINMAIL_BOOTS", "Bottes en mailles");
        translations.put("IRON_HELMET", "Casque en fer");
        translations.put("IRON_CHESTPLATE", "Plastron en fer");
        translations.put("IRON_LEGGINGS", "Jambières en fer");
        translations.put("IRON_BOOTS", "Bottes en fer");
        translations.put("DIAMOND_HELMET", "Casque en diamant");
        translations.put("DIAMOND_CHESTPLATE", "Plastron en diamant");
        translations.put("DIAMOND_LEGGINGS", "Jambières en diamant");
        translations.put("DIAMOND_BOOTS", "Bottes en diamant");
        translations.put("GOLD_HELMET", "Casque en or");
        translations.put("GOLD_CHESTPLATE", "Plastron en or");
        translations.put("GOLD_LEGGINGS", "Jambières en or");
        translations.put("GOLD_BOOTS", "Bottes en or");
        translations.put("FLINT", "Silex");
        translations.put("PORK", "Porc cru");
        translations.put("GRILLED_PORK", "Porc grillé");
        translations.put("PAINTING", "Tableau");
        translations.put("GOLDEN_APPLE", "Pomme dorée");
        translations.put("SIGN", "Panneau");
        translations.put("WOOD_DOOR", "Porte en bois");
        translations.put("BUCKET", "Seau");
        translations.put("WATER_BUCKET", "Seau d'eau");
        translations.put("LAVA_BUCKET", "Seau de lave");
        translations.put("MINECART", "Wagonnet");
        translations.put("SADDLE", "Selle");
        translations.put("IRON_DOOR", "Porte en fer");
        translations.put("REDSTONE", "Redstone");
        translations.put("SNOW_BALL", "Boule de neige");
        translations.put("BOAT", "Bateau");
        translations.put("LEATHER", "Cuir");
        translations.put("MILK_BUCKET", "Seau de lait");
        translations.put("CLAY_BRICK", "Brique");
        translations.put("CLAY_BALL", "Argile");
        translations.put("SUGAR_CANE", "Canne à sucre");
        translations.put("PAPER", "Papier");
        translations.put("BOOK", "Livre");
        translations.put("SLIME_BALL", "Boule de slime");
        translations.put("STORAGE_MINECART", "Wagonnet avec coffre");
        translations.put("POWERED_MINECART", "Wagonnet motorisé");
        translations.put("EGG", "Œuf");
        translations.put("COMPASS", "Boussole");
        translations.put("FISHING_ROD", "Canne à pêche");
        translations.put("WATCH", "Montre");
        translations.put("GLOWSTONE_DUST", "Poussière de pierre lumineuse");
        translations.put("RAW_FISH", "Poisson cru");
        translations.put("COOKED_FISH", "Poisson cuit");
        translations.put("INK_SACK", "Sac d'encre");
        translations.put("BONE", "Os");
        translations.put("SUGAR", "Sucre");
        translations.put("CAKE", "Gâteau");
        translations.put("BED", "Lit");
        translations.put("DIODE", "Répéteur");
        translations.put("COOKIE", "Cookie");
        translations.put("MAP", "Carte");
        translations.put("SHEARS", "Cisailles");
        translations.put("MELON", "Melon");
        translations.put("PUMPKIN_SEEDS", "Graines de citrouille");
        translations.put("MELON_SEEDS", "Graines de melon");
        translations.put("RAW_BEEF", "Bœuf cru");
        translations.put("COOKED_BEEF", "Steak");
        translations.put("RAW_CHICKEN", "Poulet cru");
        translations.put("COOKED_CHICKEN", "Poulet cuit");
        translations.put("ROTTEN_FLESH", "Chair putréfiée");
        translations.put("ENDER_PEARL", "Perle de l'Ender");
        translations.put("BLAZE_ROD", "Bâton de Blaze");
        translations.put("GHAST_TEAR", "Larme de Ghast");
        translations.put("GOLD_NUGGET", "Pépite d'or");
        translations.put("NETHER_STALK", "Verrue du Nether");
        translations.put("POTION", "Potion");
        translations.put("GLASS_BOTTLE", "Fiole");
        translations.put("SPIDER_EYE", "Œil d'araignée");
        translations.put("FERMENTED_SPIDER_EYE", "Œil d'araignée fermenté");
        translations.put("BLAZE_POWDER", "Poudre de Blaze");
        translations.put("MAGMA_CREAM", "Crème de magma");
        translations.put("BREWING_STAND_ITEM", "Alambic");
        translations.put("CAULDRON_ITEM", "Chaudron");
        translations.put("EYE_OF_ENDER", "Œil de l'Ender");
        translations.put("SPECKLED_MELON", "Melon scintillant");
        translations.put("MONSTER_EGG", "Œuf d'apparition");
        translations.put("EXP_BOTTLE", "Fiole d'expérience");
        translations.put("FIREBALL", "Boule de feu");
        translations.put("BOOK_AND_QUILL", "Livre et plume");
        translations.put("WRITTEN_BOOK", "Livre écrit");
        translations.put("EMERALD", "Émeraude");
        translations.put("ITEM_FRAME", "Cadre");
        translations.put("FLOWER_POT_ITEM", "Pot de fleur");
        translations.put("CARROT_ITEM", "Carotte");
        translations.put("POTATO_ITEM", "Pomme de terre");
        translations.put("BAKED_POTATO", "Pomme de terre cuite");
        translations.put("POISONOUS_POTATO", "Pomme de terre empoisonnée");
        translations.put("EMPTY_MAP", "Carte vierge");
        translations.put("GOLDEN_CARROT", "Carotte dorée");
        translations.put("SKULL_ITEM", "Crâne");
        translations.put("CARROT_STICK", "Carotte sur un bâton");
        translations.put("NETHER_STAR", "Étoile du Nether");
        translations.put("PUMPKIN_PIE", "Tarte à la citrouille");
        translations.put("FIREWORK", "Feu d'artifice");
        translations.put("FIREWORK_CHARGE", "Étoile de feu d'artifice");
        translations.put("ENCHANTED_BOOK", "Livre enchanté");
        translations.put("REDSTONE_COMPARATOR", "Comparateur");
        translations.put("NETHER_BRICK_ITEM", "Brique du Nether");
        translations.put("QUARTZ", "Quartz");
        translations.put("EXPLOSIVE_MINECART", "Wagonnet avec TNT");
        translations.put("HOPPER_MINECART", "Wagonnet avec entonnoir");
        translations.put("PRISMARINE_SHARD", "Éclat de prismarine");
        translations.put("PRISMARINE_CRYSTALS", "Cristaux de prismarine");
        translations.put("RABBIT", "Lapin cru");
        translations.put("COOKED_RABBIT", "Lapin cuit");
        translations.put("RABBIT_STEW", "Ragoût de lapin");
        translations.put("RABBIT_FOOT", "Patte de lapin");
        translations.put("RABBIT_HIDE", "Peau de lapin");
        translations.put("ARMOR_STAND", "Porte-armure");
        translations.put("IRON_BARDING", "Armure en fer pour cheval");
        translations.put("GOLD_BARDING", "Armure en or pour cheval");
        translations.put("DIAMOND_BARDING", "Armure en diamant pour cheval");
        translations.put("LEASH", "Laisse");
        translations.put("NAME_TAG", "Étiquette");
        translations.put("COMMAND_MINECART", "Wagonnet à commandes");
        translations.put("MUTTON", "Mouton cru");
        translations.put("COOKED_MUTTON", "Mouton cuit");
        translations.put("BAT", "Chauve-souris");
        translations.put("CHICKEN", "Poulet");
        translations.put("COW", "Vache");
        translations.put("MUSHROOM_COW", "Champimeuh");
        translations.put("PIG", "Cochon");
        translations.put("RABBIT", "Lapin");
        translations.put("SHEEP", "Mouton");
        translations.put("SQUID", "Poulpe");
        translations.put("VILLAGER", "Villageois");
        translations.put("HORSE", "Cheval");
        translations.put("OCELOT", "Ocelot");
        translations.put("WOLF", "Loup");
        translations.put("BLAZE", "Blaze");
        translations.put("CAVE_SPIDER", "Araignée venimeuse");
        translations.put("CREEPER", "Creeper");
        translations.put("ENDERMAN", "Enderman");
        translations.put("ENDERMITE", "Endermite");
        translations.put("GHAST", "Ghast");
        translations.put("GUARDIAN", "Gardien");
        translations.put("MAGMA_CUBE", "Cube de magma");
        translations.put("PIG_ZOMBIE", "Cochon zombie");
        translations.put("SILVERFISH", "Poisson d'argent");
        translations.put("SKELETON", "Squelette");
        translations.put("SLIME", "Slime");
        translations.put("SPIDER", "Araignée");
        translations.put("WITCH", "Sorcière");
        translations.put("WITHER_SKELETON", "Squelette du Wither");
        translations.put("ZOMBIE", "Zombie");
        translations.put("ENDER_DRAGON", "Dragon de l'Ender");
        translations.put("WITHER", "Wither");
        translations.put("ARROW", "Flèche");
        translations.put("ARMOR_STAND", "Porte-armure");
        translations.put("BOAT", "Bateau");
        translations.put("DROPPED_ITEM", "Objet au sol");
        translations.put("ENDER_CRYSTAL", "Cristal de l'Ender");
        translations.put("ENDER_PEARL", "Perle de l'Ender");
        translations.put("ENDER_SIGNAL", "Signal de l'Ender");
        translations.put("EXPERIENCE_ORB", "Orbe d'expérience");
        translations.put("FALLING_BLOCK", "Bloc en chute");
        translations.put("FIREBALL", "Boule de feu");
        translations.put("FIREWORK", "Feu d'artifice");
        translations.put("FISHING_HOOK", "Hameçon");
        translations.put("IRON_GOLEM", "Golem de fer");
        translations.put("ITEM_FRAME", "Cadre");
        translations.put("LIGHTNING", "Éclair");
        translations.put("MINECART", "Wagonnet");
        translations.put("MINECART_CHEST", "Wagonnet avec coffre");
        translations.put("MINECART_COMMAND", "Wagonnet à commandes");
        translations.put("MINECART_FURNACE", "Wagonnet motorisé");
        translations.put("MINECART_HOPPER", "Wagonnet avec entonnoir");
        translations.put("MINECART_MOB_SPAWNER", "Wagonnet avec générateur");
        translations.put("MINECART_TNT", "Wagonnet avec TNT");
        translations.put("PAINTING", "Tableau");
        translations.put("PLAYER", "Joueur");
        translations.put("PRIMED_TNT", "TNT amorcée");
        translations.put("SNOWBALL", "Boule de neige");
        translations.put("SNOWMAN", "Bonhomme de neige");
        translations.put("SPLASH_POTION", "Potion jetable");
        translations.put("THROWN_EXP_BOTTLE", "Fiole d'expérience");
        translations.put("WEATHER", "Météo");
        translations.put("WITHER_SKULL", "Tête de Wither");
    }
}
